version: '3'

services:
  informer:
    image: jontyding/informer:latest
    volumes:
      - ./data:/app/data
      - ./build/data:/app/build/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
