version: '3'
services:
  informer:
    image: jontyding/informer:latest
    container_name: informer
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - redis
    networks:
      - informer-network

  redis:
    image: redis:latest
    container_name: informer-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - informer-network

volumes:
  redis-data:

networks:
  informer-network:
    driver: bridge
